### ISSUE TITLE
Implement application to print Prime numbers

### ISSUE THREAD

**Issue by serh2i** [olyakovenko/learn-java#4]
Another "warm-up" task for you.
Implement an application which will print prime numbers from 1 to N. You don't need to enter N from keyboard, it can be hardcoded in your app. Please implement this in class called olya.exercises.misc.SimplePrimes

**Comment by serh2i** [comment]
Your implementation is plain wrong :(
It says that "0 2 4 6" are prime numbers, they are not. Reopening.

**Comment by olyakovenko** [comment]
Fixed

**Comment by serh2i** [comment]
If it's fixed you should close it :)
